---
project_name: "project_name_dev"

auth_basic_enabled: true

db_name: "{{ project_name }}"
db_user: "{{ default_user }}"
db_password: "{{ default_password }}"

django_settings_debug: True
gunicorn_workers: 1

hg_branch: default

server_hostname: server_hostname.online
server_ssl_enabled: false
