---
- name: Install virtualenv via pip
  become: true
  pip:
    name: virtualenv

- name: Check if virtual environment already exists
  stat:
    path: "/home/{{ default_user }}/.virtualenvs/{{ project_name }}"
  register: virtualenv_exists
  changed_when: false

- name: Creating virtual environment
  shell: "virtualenv {{ virtualenv_path }} -p {{ ansible_python_interpreter }} creates={{ virtualenv_path }}"
  when: virtualenv_exists.stat.exists==false