---
- name: create a new user
  user:
    name: "{{ default_user }}"
    password: "{{ default_password|password_hash('sha512', 'secret_salt!') }}"
    shell: /bin/bash
    state: present
  register: create_user

- name: grant sudo priveleges to a new user
  shell: "usermod -aG sudo {{ default_user }}"
  when: create_user.changed

- name: ensure users .ssh directory exists
  file:
    path: "/home/{{ default_user }}/.ssh"
    state: directory
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: 0700

- name: Set root's authorized key for a new user
  copy:
    remote_src: true
    src: "/root/.ssh/authorized_keys"
    dest: "/home/{{ default_user }}/.ssh/authorized_keys"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: 0600